<?xml version="1.0" ?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="inertial_macros.xacro"/>

	<!-- Constants -->
	<xacro:property name="pi_const" value="3.14159265356" />
	<xacro:property name="half_pi_const" value="1.570796" />


	<!-- Material colors -->
	<material name="white">
		<color rgba="1.0 1.0 1.0 1.0"/>
	</material>

	<material name="yellow">
		<color rgba="1.0 0.9 0.0 1.0"/>
	</material>

	<material name="green">
		<color rgba="0.0 0.8 0.0 1.0"/>
	</material>

	<material name="red">
		<color rgba="0.8 0.0 0.0 1.0"/>
	</material>


	<!-- Body geometry -->
	<xacro:property name="body_link_x_dim" value="0.18" />
	<xacro:property name="body_link_y_dim" value="0.22" />
	<xacro:property name="body_link_z_dim" value="0.175" />
	<xacro:property name="body_link_z_offset" value="0.035" />
	<xacro:property name="body_mass" value="0.5" />

	<!-- Wheel geometry -->
	<xacro:property name="wheel_link_radius" value="0.06" />
	<xacro:property name="wheel_link_length" value="0.0325" />
	<xacro:property name="wheel_link_x_location" value="0.105" />
	<xacro:property name="wheel_suport_y_offset" value="0.075"/>
	<xacro:property name="wheel_link_mass" value="0.1"/>

	<!-- Sphere geometry -->
	<xacro:property name="sphere_radius" value="0.045" />
	<xacro:property name="sphere_x_offset" value="0.035"/>
	<xacro:property name="sphere_mass" value="0.1" />

	<!-- base link-->
	<link name="base_link">
		<origin xyz= "0 0 0" />
	</link>

	<!-- Chassis -->
	<joint name="chassis_joint" type="fixed">
		<parent link = "base_link"/>
		<child link = "chassis_link"/>
		<origin xyz="-${wheel_link_x_location} 0 ${wheel_link_radius + body_link_z_offset}"/>
	</joint>

	<link name="chassis_link">
		<visual>
			<origin xyz="${body_link_x_dim/2} 0 ${body_link_z_dim/2}"/>
			<geometry>
				<box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<origin xyz="${body_link_x_dim/2} 0 ${body_link_z_dim/2}"/>
			<geometry>
				<box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
			</geometry>
        </collision>
        <xacro:inertial_box mass="${body_mass}" x="${body_link_x_dim}" y="${body_link_y_dim}" z="${body_link_z_dim}">
            <origin xyz="${body_link_x_dim/2} 0 ${body_link_z_dim/2}" rpy="0 0 0" />
        </xacro:inertial_box>
	</link>

	<!-- right_wheel_link -->
	<joint name="right_wheel_joint" type="fixed">
		<origin xyz="0 -${body_link_y_dim/2 + wheel_suport_y_offset} ${wheel_link_radius}" rpy="${pi_const/2} 0 0"/>
		<parent link="base_link"/>
		<child link="right_wheel_link"/>
		<axis xyz="0 0 -1" />
	</joint>

	<link name="right_wheel_link">
		<visual>
			<geometry>
				<cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
			</geometry>
			<material name ="yellow" />
		</visual>
		<collision>
            <geometry>
				<cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
			</geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_link_mass}" length="${wheel_link_length}" radius="${wheel_link_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
	</link>

	<!-- left_wheel_link -->
	<joint name="left_wheel_joint" type="fixed">
		<origin xyz="0 ${body_link_y_dim/2 + wheel_suport_y_offset} ${wheel_link_radius}" rpy="${pi_const/2} 0 0"/>
		<parent link="base_link"/>
		<child link="left_wheel_link"/>
		<axis xyz="0 0 1" />
	</joint>

	<link name="left_wheel_link">
		<visual>
			<geometry>
				<cylinder radius="${wheel_link_radius}" length = "${wheel_link_length}"/>
			</geometry>
			<material name ="yellow" />
		</visual>
		<collision>
			<geometry>
				<cylinder radius="${wheel_link_radius}" length = "${wheel_link_length}"/>
			</geometry>
		</collision>
		<xacro:inertial_cylinder mass="${wheel_link_mass}" length="${wheel_link_length}" radius="${wheel_link_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
	</link>
		
	<!-- caster wheel -->
	<joint name="caster_wheel_joint" type="fixed">
		<parent link="base_link"/>
		<child link="caster_wheel_link"/>
		<origin xyz="-${wheel_link_x_location + sphere_x_offset} 0 ${sphere_radius}" rpy="0 0 0"/>
	</joint>
 
	<link name="caster_wheel_link">
		<visual>
			<geometry>
				<sphere radius="${sphere_radius}" />
			</geometry>
			<material name ="green" />
		</visual>
		<collision>
			<geometry>
				<sphere radius="${sphere_radius}" />
			</geometry>
		</collision>
		<xacro:inertial_sphere mass="${sphere_mass}" radius="${sphere_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_sphere>
	</link>

</robot>
